### ISSUE TITLE
Bad Code

### ISSUE THREAD

**Issue by ghandhikus** [matttomasetti/Java-WebSocket_Websocket-Benchmark-Server#1]
https://github.com/matttomasetti/Java-WebSocket_Websocket-Benchmark-Server/blame/d235edf6bf6eac22ed3c35e207db6b66af685869/src/main/java/Main/Server.java#L104

This code is just horrible. [JsonParser](https://docs.oracle.com/javaee/7/api/javax/json/stream/JsonParser.html) extends [Closeable](http://docs.oracle.com/javase/7/docs/api/java/io/Closeable.html?is-external=true) which requires you to close it in order to get rid of the resources. You are not caching it either. EDIT: Forgot to mention. Yes it is a memory leak.

On top of that you are using System.out.println which stops the thread from executing until the message is sent to the OS. Logging should be done with a proper logging library that off-loads the job from the thread using it.

Also, you are creating a HashMap literally every single time you want to make a very simple object https://github.com/matttomasetti/Java-WebSocket_Websocket-Benchmark-Server/blob/master/src/main/java/Main/Server.java#L158
See this java source code: https://android.googlesource.com/platform/dalvik/+/f2f7880a40aed1c8d9c27db49226e47396556aac/libcore/json/src/main/java/org/json/JSONObject.java#112

Why would you even make a paper on language comparison if you don't know how to use the language?

**Comment by matttomasetti** [comment]
@ghandhikus, It is unfortunate that Java and it's standard extensions do not meet your desired performance expectations. Closing issue due to irrelevance.

**Comment by CordlessCoder** [comment]
@matttomasetti If you could care to read the objection, you'd know it has nothing to do with "performance of Java and it's standard extensions" and everything with the fact that your implementation is subpar.
They've highlighted how it is and left you with a very actionable piece of criticism it wouldn't take that long to implement.
But instead of actually using their advice as an opportunity to improve this project and the accuracy of its results, you jumped to your non sequitur of "I'm sorry that Java is bad" and claimed irrelevance.
If you don't care about the quality of the benchmark, why write a paper about it?
